// Copyright 2026 evanwboyle and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"yalie-pp-cli/internal/client"
	"yalie-pp-cli/internal/cliutil"

	"github.com/spf13/cobra"
)

// pp:data-source live
//
// Calls the live Canvas API directly on every invocation — there is no local
// file-listing cache, so this command does not honor --data-source local.
func newCanvasFilesListCmd(flags *rootFlags) *cobra.Command {
	var flagPath string

	cmd := &cobra.Command{
		Use:   "list <course_id>",
		Short: "List a Canvas course's files (metadata only)",
		Long: "List a Canvas course's file directory: names, sizes, folders, IDs. Deliberately " +
			"does not fetch file contents — some Files sections contain entire textbooks; " +
			"auto-fetching would flood context. Use 'canvas files get --file <id>' to fetch one " +
			"specific file at a time after reviewing this listing.\n\n" +
			"Pass --path to browse into a specific folder (e.g. \"Readings\" or \"Readings/Week1\") " +
			"instead of listing the whole course — the path is resolved against Canvas's folder " +
			"tree first, then only that folder's files are listed.",
		Example:     "  yalie-pp-cli canvas files list 89687\n  yalie-pp-cli canvas files list 89687 --path \"Readings\"",
		Annotations: map[string]string{"pp:endpoint": "files.list", "pp:method": "GET", "pp:path": "/courses/{course_id}/files", "mcp:read-only": "true", "pp:data-source": "live"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <course_id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <course_id>"))
			}
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("course_id is required\nUsage: %s <%s>", cmd.CommandPath(), "course_id"))
			}
			path := "/courses/{course_id}/files"
			path = replacePathParam(path, "course_id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			if trimmedPath := strings.Trim(strings.TrimSpace(flagPath), "/"); trimmedPath != "" {
				folderID, ferr := resolveCanvasFolderPath(cmd, c, flags, args[0], trimmedPath)
				if ferr != nil {
					return ferr
				}
				path = replacePathParam("/folders/{folder_id}/files", "folder_id", folderID)
			}
			data, prov, err := resolveReadWithStrategyAndResponsePath(cmd.Context(), c, flags, "live", "files", false, path, params, nil, "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			outputData := data
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(outputData, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered, map[string]bool{"content-type": true, "display_name": true, "filename": true, "folder_id": true, "id": true, "size": true, "updated_at": true, "url": true})
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				wrapped, wrapErr = wrapPlatformStructuredOutput(wrapped, flags, "results", true)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"}, map[string]bool{"content-type": true, "display_name": true, "filename": true, "folder_id": true, "id": true, "size": true, "updated_at": true, "url": true})
		},
	}
	cmd.Flags().StringVar(&flagPath, "path", "", "Folder path to browse within the course's file directory (e.g. \"Readings\")")

	return cmd
}

// resolveCanvasFolderPath resolves a human-readable folder path (e.g.
// "Readings/Week1") within a Canvas course's file directory to the numeric
// folder ID Canvas needs for a folder-scoped file listing. It calls Canvas's
// folder-resolution endpoint (GET /courses/{course_id}/folders/by_path/{full_path}),
// which returns the chain of folder objects from the course root down to the
// requested folder; the last entry's ID is the folder we want to list files in.
func resolveCanvasFolderPath(cmd *cobra.Command, c *client.Client, flags *rootFlags, courseID string, folderPath string) (string, error) {
	segments := strings.Split(folderPath, "/")
	escaped := make([]string, 0, len(segments))
	for _, segment := range segments {
		if segment == "" {
			continue
		}
		escaped = append(escaped, cliutil.EscapePathParam(segment))
	}
	resolvePath := replacePathParam("/courses/{course_id}/folders/by_path/"+strings.Join(escaped, "/"), "course_id", courseID)
	data, _, err := resolveReadWithStrategyAndResponsePath(cmd.Context(), c, flags, "live", "files", true, resolvePath, map[string]string{}, nil, "", cmd.ErrOrStderr())
	if err != nil {
		return "", classifyAPIError(cmd.OutOrStdout(), err, flags)
	}
	var folders []struct {
		ID json.Number `json:"id"`
	}
	if err := json.Unmarshal(data, &folders); err != nil || len(folders) == 0 {
		return "", usageErr(fmt.Errorf("could not resolve folder path %q in course %s: no such folder", folderPath, courseID))
	}
	folderID := folders[len(folders)-1].ID.String()
	if folderID == "" {
		return "", usageErr(fmt.Errorf("could not resolve folder path %q in course %s: folder had no id", folderPath, courseID))
	}
	return folderID, nil
}
