// Copyright 2026 evanwboyle and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCanvasFilesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "files",
		Short: "Browse a Canvas course's file directory (metadata only, no auto-download)",
		Long: "Browse a Canvas course's Files directory, or fetch one specific file by ID.\n\n" +
			"List a course's Files directory before fetching — NEVER bulk-fetch every file in " +
			"one call. Some Files sections contain entire textbooks; auto-fetching would flood " +
			"context. Use 'canvas files list' to see the directory, then 'canvas files get " +
			"--file <id>' for one explicit file at a time.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCanvasFilesListCmd(flags))
	cmd.AddCommand(newCanvasFilesGetCmd(flags))
	return cmd
}
