// Copyright 2026 evanwboyle and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"yalie-pp-cli/internal/cli"
	"yalie-pp-cli/internal/client"
	"yalie-pp-cli/internal/cliutil"
	"yalie-pp-cli/internal/config"
	"yalie-pp-cli/internal/learn"
	"yalie-pp-cli/internal/mcp/bound"
	"yalie-pp-cli/internal/mcp/cobratree"
	"yalie-pp-cli/internal/platform"
	"yalie-pp-cli/internal/store"
)

const (
	// MCP hosts can fan out tool calls faster than a human CLI session.
	// Keep them on the same polite-client limiter path instead of disabling
	// pacing with rate=0; users can still tune human CLI calls with --rate-limit.
	defaultMCPRateLimit = 2

	// yalieCookieAuthHintMCP mirrors internal/cli/helpers.go's yalieCookieAuthHint.
	// DEVIATION FROM GENERATOR TEMPLATE: see that file for the full rationale —
	// three of four data sources here authenticate via a raw session cookie env
	// var, not the spec-declared Bearer token, and the generated hint text only
	// ever suggested Bearer setup. Regen will overwrite this.
	yalieCookieAuthHintMCP = "\n      This CLI also supports cookie-based auth for CourseTable/Degree Audit/Canvas — " +
		"if you're using COURSETABLE_COOKIE, AUDIT_COOKIE, or CANVAS_COOKIE, re-check that the cookie is still valid " +
		"and copied from a fresh logged-in tab (Yale CAS sessions expire), rather than setting a bearer token."
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	installFreshTenantGate(s)
	s.AddTool(
		mcplib.NewTool("courses_assignments_get",
			mcplib.WithDescription("Get a Canvas assignment's detail. Required: course_id, id. Returns the Assignment."),
			mcplib.WithNumber("course_id", mcplib.Required(), mcplib.Description("Course id")),
			mcplib.WithNumber("id", mcplib.Required(), mcplib.Description("Id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/courses/{course_id}/assignments/{id}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "course_id", WireName: "course_id", Location: "path"}, {PublicName: "id", WireName: "id", Location: "path"}}, []string{"course_id", "id"}),
	)
	s.AddTool(
		mcplib.NewTool("courses_assignments_list",
			mcplib.WithDescription("List a Canvas course's assignments. Required: course_id. Returns array of Assignment."),
			mcplib.WithNumber("course_id", mcplib.Required(), mcplib.Description("Course id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/courses/{course_id}/assignments", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "course_id", WireName: "course_id", Location: "path"}}, []string{"course_id"}),
	)
	s.AddTool(
		mcplib.NewTool("courses_enrollments_get-grades",
			mcplib.WithDescription("Get the student's grades/enrollment for a Canvas course. Required: course_id. Optional: user_id (default: self). Returns array of Enrollment."),
			mcplib.WithNumber("course_id", mcplib.Required(), mcplib.Description("Course id")),
			mcplib.WithString("user_id", mcplib.Description("User id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/courses/{course_id}/enrollments", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "course_id", WireName: "course_id", Location: "path"}, {PublicName: "user_id", WireName: "user_id", Location: "query", Default: "self"}}, []string{"course_id"}),
	)
	s.AddTool(
		mcplib.NewTool("courses_files_list",
			mcplib.WithDescription("List a Canvas course's files (metadata only). Required: course_id. Returns array of CanvasFile."),
			mcplib.WithNumber("course_id", mcplib.Required(), mcplib.Description("Course id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/courses/{course_id}/files", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "course_id", WireName: "course_id", Location: "path"}}, []string{"course_id"}),
	)
	s.AddTool(
		mcplib.NewTool("courses_pages_get",
			mcplib.WithDescription("Get a Canvas course page's content by its URL slug. Required: course_id, url. Returns the Page."),
			mcplib.WithNumber("course_id", mcplib.Required(), mcplib.Description("Course id")),
			mcplib.WithString("url", mcplib.Required(), mcplib.Description("Url")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/courses/{course_id}/pages/{url}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "course_id", WireName: "course_id", Location: "path"}, {PublicName: "url", WireName: "url", Location: "path"}}, []string{"course_id", "url"}),
	)
	s.AddTool(
		mcplib.NewTool("courses_pages_list",
			mcplib.WithDescription("List a Canvas course's pages. Required: course_id. Returns array of Page."),
			mcplib.WithNumber("course_id", mcplib.Required(), mcplib.Description("Course id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/courses/{course_id}/pages", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "course_id", WireName: "course_id", Location: "path"}}, []string{"course_id"}),
	)
	s.AddTool(
		mcplib.NewTool("courses_quizzes_get-quiz",
			mcplib.WithDescription("Get a Canvas quiz's detail. Required: course_id, id. Returns the Quiz."),
			mcplib.WithNumber("course_id", mcplib.Required(), mcplib.Description("Course id")),
			mcplib.WithNumber("id", mcplib.Required(), mcplib.Description("Id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/courses/{course_id}/quizzes/{id}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "course_id", WireName: "course_id", Location: "path"}, {PublicName: "id", WireName: "id", Location: "path"}}, []string{"course_id", "id"}),
	)
	s.AddTool(
		mcplib.NewTool("courses_quizzes_list",
			mcplib.WithDescription("List a Canvas course's quizzes. Required: course_id. Returns array of Quiz."),
			mcplib.WithNumber("course_id", mcplib.Required(), mcplib.Description("Course id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/courses/{course_id}/quizzes", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "course_id", WireName: "course_id", Location: "path"}}, []string{"course_id"}),
	)
	s.AddTool(
		mcplib.NewTool("files_get",
			mcplib.WithDescription("Get metadata + download URL for one Canvas file by ID. Required: id. Returns the CanvasFile."),
			mcplib.WithNumber("id", mcplib.Required(), mcplib.Description("Id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/files/{id}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Synced records live in resources(resource_type, id, data); filter by resource_type and use json_extract on data, e.g. SELECT json_extract(data,'$.name') FROM resources WHERE resource_type='courses'.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
	Default    string
}

type mcpPageConfig struct {
	CursorParam    string
	NextCursorPath string
}

func formatMCPParamValue(v any) string {
	switch tv := v.(type) {
	case string:
		return tv
	case bool:
		return strconv.FormatBool(tv)
	case float64:
		if math.IsNaN(tv) || math.IsInf(tv, 0) {
			return strconv.FormatFloat(tv, 'f', -1, 64)
		}
		if math.Trunc(tv) == tv && math.Abs(tv) < 1e15 {
			return strconv.FormatInt(int64(tv), 10)
		}
		return strconv.FormatFloat(tv, 'f', -1, 64)
	case float32:
		f := float64(tv)
		if math.IsNaN(f) || math.IsInf(f, 0) {
			return strconv.FormatFloat(f, 'f', -1, 32)
		}
		if math.Trunc(f) == f && math.Abs(f) < 1e15 {
			return strconv.FormatInt(int64(f), 10)
		}
		return strconv.FormatFloat(f, 'f', -1, 32)
	default:
		// Composite values (a native []any / map[string]any from an array or
		// object param) reach this path when bound to a query or path slot;
		// JSON-encode them so the wire value is valid JSON rather than Go's
		// "[a b c]" / "map[...]" rendering. Body params never come through
		// here — they are stored natively in bodyArgs and marshalled there.
		if b, err := json.Marshal(v); err == nil {
			return string(b)
		}
		return fmt.Sprintf("%v", v)
	}
}

func mcpPathValue(v any) string {
	return cliutil.EscapePathParam(formatMCPParamValue(v))
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, readOnly bool, binaryResponse bool, headerOverrides map[string]string, pageConfig mcpPageConfig, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, platformSession, err := newMCPClient(ctx)
		if err != nil {
			return mcpToolError(err.Error()), nil
		}
		if platformSession != nil {
			defer platformSession.ZeroCredentials()
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()
		if err := cli.AdoptMCPOutputSemantics(platformSession, args); err != nil {
			return mcpToolError(err.Error()), nil
		}

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		mcpCursor := ""
		if pageConfig.CursorParam != "" {
			knownArgs["cursor"] = true
			if v, ok := args["cursor"]; ok {
				s, ok := v.(string)
				if !ok {
					return mcpToolError("cursor must be an opaque string returned by a previous MCP response"), nil
				}
				mcpCursor = s
				upstreamCursor, err := bound.UpstreamCursor(s)
				if err != nil {
					return mcpToolError(err.Error()), nil
				}
				if upstreamCursor != "" {
					params[pageConfig.CursorParam] = upstreamCursor
				}
			}
		}
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				if binding.Default != "" {
					v = binding.Default
				} else {
					continue
				}
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, mcpPathValue(v), 1)
			case "header":
				if headers == nil {
					headers = map[string]string{}
				}
				headers[binding.WireName] = formatMCPParamValue(v)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = formatMCPParamValue(v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, mcpPathValue(v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = formatMCPParamValue(v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				if readOnly {
					data, err = c.GetWithHeaders(ctx, path, params, headers)
				} else {
					data, err = c.GetMutatingWithHeaders(ctx, path, params, headers)
				}
				break
			}
			if readOnly {
				data, err = c.Get(ctx, path, params)
			} else {
				data, err = c.GetMutating(ctx, path, params)
			}
		case "POST":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PostQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PostWithParams(ctx, path, params, bodyArgs)
			}
		case "PUT":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PutQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PutQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PutWithParams(ctx, path, params, bodyArgs)
			}
		case "PATCH":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PatchQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PatchQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PatchWithParams(ctx, path, params, bodyArgs)
			}
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(ctx, path, params)
		default:
			return mcpToolError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcpToolTextWithPlatform("already exists (no-op)", platformSession), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcpToolError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set it with: echo \"$TOKEN\" | yalie-pp-cli auth set-token or export YALIE_BEARER_AUTH=\"your-token-here\"" +
					yalieCookieAuthHintMCP +
					"\n      Run 'yalie-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcpToolError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your token." +
					"\n      Set it with: echo \"$TOKEN\" | yalie-pp-cli auth set-token or export YALIE_BEARER_AUTH=\"your-token-here\"" +
					yalieCookieAuthHintMCP +
					"\n      Run 'yalie-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcpToolError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource. Check that they have the required permissions and match the API's expected auth scheme." +
					"\n      Set it with: echo \"$TOKEN\" | yalie-pp-cli auth set-token or export YALIE_BEARER_AUTH=\"your-token-here\"" +
					yalieCookieAuthHintMCP +
					"\n      Run 'yalie-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcpToolTextWithPlatform("already deleted (no-op)", platformSession), nil
				}
				return mcpToolError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcpToolError("rate limited: " + msg), nil
			default:
				return mcpToolError(msg), nil
			}
		}

		if binaryResponse {
			encoded := base64.StdEncoding.EncodeToString(data)
			out, err := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      encoded,
				"byte_count":       len(data),
			})
			if err != nil {
				return mcpToolError(fmt.Sprintf("encoding binary result: %v", err)), nil
			}
			if len(out) > bound.MaxBytes {
				return mcpToolError(fmt.Sprintf("binary response is too large for MCP text output: %d response bytes encode to %d base64 bytes and %d MCP result bytes, exceeding the %d byte budget. Use the companion CLI command with --output <file> to save the payload locally.", len(data), len(encoded), len(out), bound.MaxBytes)), nil
			}
			result := string(out)
			if platformSession != nil {
				result = bound.WithMetadata(result, platformSession.OutputMetadata())
			}
			return mcplib.NewToolResultText(result), nil
		}
		if pageConfig.CursorParam != "" {
			return mcpToolPageResultTextWithPlatform(method, data, pageConfig, mcpCursor, platformSession), nil
		}
		return mcpToolResultTextWithPlatform(method, data, platformSession), nil
	}
}

func mcpToolResultText(method string, data json.RawMessage) *mcplib.CallToolResult {
	return mcpToolResultTextWithPlatform(method, data, nil)
}

func mcpToolTextWithPlatform(result string, platformSession *platform.Session) *mcplib.CallToolResult {
	if platformSession != nil {
		result = bound.WithMetadata(result, platformSession.OutputMetadata())
	}
	return mcplib.NewToolResultText(result)
}

func mcpToolResultTextWithPlatform(method string, data json.RawMessage, platformSession *platform.Session) *mcplib.CallToolResult {
	result := bound.EndpointResponse(method, data)
	return mcpToolTextWithPlatform(result, platformSession)
}

// mcpToolError keeps provider-controlled typed endpoint errors within the MCP
// text-result budget just like successful endpoint results.
func mcpToolError(message string) *mcplib.CallToolResult {
	return mcplib.NewToolResultError(bound.Text(message))
}

func mcpToolPageResultText(method string, data json.RawMessage, pageConfig mcpPageConfig, cursor string) *mcplib.CallToolResult {
	return mcpToolPageResultTextWithPlatform(method, data, pageConfig, cursor, nil)
}

func mcpToolPageResultTextWithPlatform(method string, data json.RawMessage, pageConfig mcpPageConfig, cursor string, platformSession *platform.Session) *mcplib.CallToolResult {
	result := bound.EndpointPageResponse(method, data, bound.PageOptions{
		Cursor:         cursor,
		CursorParam:    pageConfig.CursorParam,
		NextCursorPath: pageConfig.NextCursorPath,
	})
	if platformSession != nil {
		result = bound.WithMetadata(result, platformSession.OutputMetadata())
	}
	return mcplib.NewToolResultText(result)
}

func newMCPClient(ctx context.Context) (*client.Client, *platform.Session, error) {
	cfg, err := newMCPConfig()
	if err != nil {
		return nil, nil, err
	}
	c := newMCPClientFromConfig(cfg)
	session, err := cli.BindMCPClient(ctx, c)
	if err != nil {
		return nil, nil, err
	}
	return c, session, nil
}

func newMCPConfig() (*config.Config, error) {
	cfg, err := config.Load("")
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	return cfg, nil
}

func newMCPClientFromConfig(cfg *config.Config) *client.Client {
	c := client.New(cfg, 60*time.Second, defaultMCPRateLimit)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c
}

func mcpDBPath() (string, error) {
	dir, err := cliutil.DataDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "data.db"), nil
}

type mcpStoreStatusKind string

const (
	mcpStoreStatusEmpty mcpStoreStatusKind = "empty"
	mcpStoreStatusReady mcpStoreStatusKind = "ready"
)

func openMCPReadOnlyStore(path string) (*store.Store, *mcplib.CallToolResult) {
	if _, err := os.Stat(path); err != nil {
		if os.IsNotExist(err) {
			return nil, mcplib.NewToolResultError(mcpMissingStoreMessage(path))
		}
		return nil, mcplib.NewToolResultError(fmt.Sprintf("checking local data store %s: %v", path, err))
	}
	db, err := store.OpenReadOnly(path)
	if err != nil {
		return nil, mcplib.NewToolResultError(fmt.Sprintf("opening local data store %s: %v. Use live endpoint MCP tools for unsynced data, or populate the local store through a store-backed command.", path, err))
	}
	return db, nil
}

func mcpMissingStoreMessage(path string) string {
	return fmt.Sprintf("No local data store found at %s. Use live endpoint MCP tools for unsynced data, or populate the local store through a store-backed command.", path)
}

func mcpStoreStatus(db *store.Store) (mcpStoreStatusKind, error) {
	status, err := db.Status()
	if err != nil {
		return "", err
	}
	if len(status) == 0 {
		return mcpStoreStatusEmpty, nil
	}
	return mcpStoreStatusReady, nil
}

func mcpEmptyStoreNextStep() string {
	return "The local SQLite store is empty. Use live endpoint MCP tools or populate the store through a store-backed command before using MCP search/sql."
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate rejects multi-statement input, then applies an allowlist (SELECT or
// WITH only) AFTER stripping the leading whitespace, line comments, block
// comments, and semicolons that SQLite itself ignores before parsing. A naive
// HasPrefix check on a keyword blocklist is bypassable by prefixing the
// dangerous statement with "/* x */" or "-- x\n"; a naive leading-keyword
// allowlist is bypassable by appending "; ATTACH DATABASE ...". Combined with
// the empirical fact that modernc.org/sqlite's mode=ro does NOT block VACUUM
// INTO (writes a snapshot to a new file) or ATTACH DATABASE (opens a separate
// writable handle), either bypass produces silent exfiltration to an
// attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	stripped := stripLeadingSQLNoise(query)
	if hasTrailingSQLStatement(stripped) {
		return fmt.Errorf("only a single SELECT or WITH statement is allowed")
	}
	upper := strings.ToUpper(stripped)
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

// hasTrailingSQLStatement reports whether query contains a statement
// terminator followed by more executable SQL. A trailing semicolon is allowed;
// a second statement is not. Semicolons inside string literals, quoted
// identifiers, bracket identifiers, and comments are ignored to match SQLite's
// parser shape closely enough for this security gate.
func hasTrailingSQLStatement(query string) bool {
	inSingle := false
	inDouble := false
	inBacktick := false
	inBracket := false
	inLineComment := false
	inBlockComment := false

	for i := 0; i < len(query); i++ {
		ch := query[i]
		next := byte(0)
		if i+1 < len(query) {
			next = query[i+1]
		}

		switch {
		case inLineComment:
			if ch == '\n' {
				inLineComment = false
			}
			continue
		case inBlockComment:
			if ch == '*' && next == '/' {
				inBlockComment = false
				i++
			}
			continue
		case inSingle:
			if ch == '\'' {
				if next == '\'' {
					i++
					continue
				}
				inSingle = false
			}
			continue
		case inDouble:
			if ch == '"' {
				if next == '"' {
					i++
					continue
				}
				inDouble = false
			}
			continue
		case inBacktick:
			if ch == '`' {
				if next == '`' {
					i++
					continue
				}
				inBacktick = false
			}
			continue
		case inBracket:
			if ch == ']' {
				inBracket = false
			}
			continue
		}

		switch {
		case ch == '-' && next == '-':
			inLineComment = true
			i++
		case ch == '/' && next == '*':
			inBlockComment = true
			i++
		case ch == '\'':
			inSingle = true
		case ch == '"':
			inDouble = true
		case ch == '`':
			inBacktick = true
		case ch == '[':
			inBracket = true
		case ch == ';':
			if stripLeadingSQLNoise(query[i+1:]) != "" {
				return true
			}
			return false
		}
	}
	return false
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	path, err := mcpDBPath()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("resolving database: %v", err)), nil
	}
	db, toolErr := openMCPReadOnlyStore(path)
	if toolErr != nil {
		return toolErr, nil
	}
	defer db.Close()

	rows, err := db.DB().QueryContext(ctx, query)
	if err != nil {
		return mcplib.NewToolResultError(mcpSQLQueryError(err)), nil
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading columns: %v", err)), nil
	}
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return mcplib.NewToolResultError(fmt.Sprintf("scanning row: %v", err)), nil
		}
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}
	// rows.Next() stops on a mid-iteration error without failing the loop, so
	// skipping rows.Err() would return a truncated result set as success.
	if err := rows.Err(); err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading rows: %v", err)), nil
	}
	storeStatus, err := mcpStoreStatus(db)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading store status: %v", err)), nil
	}

	return toolResultJSON(mcpSQLEnvelope(results, cols, storeStatus))
}

func mcpSQLEnvelope(rows []map[string]any, columns []string, storeStatus mcpStoreStatusKind) map[string]any {
	if rows == nil {
		rows = []map[string]any{}
	}
	out := map[string]any{
		"count":        len(rows),
		"columns":      columns,
		"rows":         rows,
		"store_status": storeStatus,
		"resumable":    false,
	}
	if len(rows) == 0 {
		if storeStatus == mcpStoreStatusEmpty {
			out["next_step"] = mcpEmptyStoreNextStep()
		} else {
			out["next_step"] = "The read-only SQL query returned no rows. Check resource_type filters, json_extract paths."
		}
	}
	return out
}

func mcpSQLQueryError(err error) string {
	msg := err.Error()
	if strings.Contains(strings.ToLower(msg), "no such table") {
		return fmt.Sprintf("query failed: %v. Synced records live in resources(resource_type, id, data), not one SQL table per resource. Filter by resource_type, for example resource_type='courses', and read JSON fields with json_extract(data,'$.field').", err)
	}
	return fmt.Sprintf("query failed: %v", err)
}

// toolResultJSON renders v as the indented JSON body of an MCP text result,
// surfacing a marshal failure as a tool error instead of empty content.
func toolResultJSON(v any) (*mcplib.CallToolResult, error) {
	text, err := bound.JSON(v)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding result: %v", err)), nil
	}
	return mcplib.NewToolResultText(text), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	paths := map[string]string{}
	if dir, err := cliutil.ConfigDir(); err == nil {
		paths["config_dir"] = dir
	}
	if dir, err := cliutil.DataDir(); err == nil {
		paths["data_dir"] = dir
	}
	if dir, err := cliutil.StateDir(); err == nil {
		paths["state_dir"] = dir
	}
	if dir, err := cliutil.CacheDir(); err == nil {
		paths["cache_dir"] = dir
	}
	ctx := map[string]any{
		"api":         "yalie",
		"description": "Every Yale academic tool YalieMCP had, plus offline course search, degree-audit history, and cross-source requirement matching no other Yale tool offers.",
		"archetype":   "content",
		"tool_count":  9,
		"paths":       paths,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion yalie-pp-cli binary.",
		// learn_protocol is generated from the single shared source of
		// truth (the exported constant internal/learn.RecallFirstProtocol)
		// also consumed by the CLI agent-context command, so the MCP and
		// CLI agent surfaces cannot drift.
		"learn_protocol": learn.RecallFirstProtocol,
		"auth": map[string]any{
			"type": "bearer_token",
			"env_vars": []map[string]any{
				{
					"name":        "YALIE_BEARER_AUTH",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
		},
		"resources": []map[string]any{
			{
				"name":        "courses",
				"description": "Manage courses",
				"endpoints":   []string{},
			},
			{
				"name":        "courses.assignments",
				"description": "Manage assignments",
				"endpoints":   []string{"get", "list"},
			},
			{
				"name":        "courses.enrollments",
				"description": "Manage enrollments",
				"endpoints":   []string{"get-grades"},
			},
			{
				"name":        "courses.files",
				"description": "Manage files",
				"endpoints":   []string{"list"},
			},
			{
				"name":        "courses.pages",
				"description": "Manage pages",
				"endpoints":   []string{"get", "list"},
			},
			{
				"name":        "courses.quizzes",
				"description": "Manage quizzes",
				"endpoints":   []string{"get-quiz", "list"},
			},
			{
				"name":        "files",
				"description": "Manage files",
				"endpoints":   []string{"get"},
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": []map[string]string{
			{"name": "Next-Course Recommender", "command": "audit recommend", "description": "See which of your remaining degree requirements have the best-rated available courses", "rationale": "Requires joining your local degree-audit unmet-requirement blocks with locally-synced course evaluation ratings — no", "via": "mcp-command-mirror"},
			{"name": "Worksheet Schedule Conflict Checker", "command": "worksheet conflicts", "description": "Flags real time overlaps between courses already saved in a worksheet, before you find out the hard way.", "rationale": "Requires decoding and comparing meeting-time bitmasks across every course in a worksheet — no CourseTable API endpoint", "via": "mcp-command-mirror"},
			{"name": "Worksheet Syllabus Search", "command": "worksheet syllabus-search", "description": "Search for a keyword or policy (e.g.", "rationale": "Requires local full-text search over previously-fetched syllabus text spanning multiple courses — no batch", "via": "mcp-command-mirror"},
			{"name": "Hypothetical Major Fit Checker", "command": "majors fit", "description": "Check how much of a major's requirements your existing course history already satisfies, without declaring it.", "rationale": "Requires matching real course history from degree audit against a scraped catalog major's requirement text — no", "via": "mcp-command-mirror"},
			{"name": "Hypothetical Certificate Fit Checker", "command": "certificates fit", "description": "Check how much of a certificate program's requirements your existing course history already satisfies", "rationale": "Same join pattern as the major fit checker", "via": "mcp-command-mirror"},
			{"name": "Canvas Course File Browser", "command": "canvas files list", "description": "Browse a Canvas course's file directory (names, sizes, folders)", "rationale": "Some Canvas Files sections contain entire textbooks; auto-fetching everything would flood context.", "via": "mcp-command-mirror"},
		},
		"playbook": []map[string]string{
			{"topic": "Next-Course Recommender", "insight": "Requires joining your local degree-audit unmet-requirement blocks with locally-synced course evaluation ratings — no single API call correlates these two sources."},
			{"topic": "Worksheet Schedule Conflict Checker", "insight": "Requires decoding and comparing meeting-time bitmasks across every course in a worksheet — no CourseTable API endpoint does this."},
			{"topic": "Worksheet Syllabus Search", "insight": "Requires local full-text search over previously-fetched syllabus text spanning multiple courses — no batch syllabus-search endpoint exists anywhere."},
			{"topic": "Hypothetical Major Fit Checker", "insight": "Requires matching real course history from degree audit against a scraped catalog major's requirement text — no declaration flow or API join exists for this today."},
			{"topic": "Hypothetical Certificate Fit Checker", "insight": "Same join pattern as the major fit checker: matches real course history against a scraped catalog certificate's requirement text — no declaration flow or API join exists for this today."},
			{"topic": "Canvas Course File Browser", "insight": "Some Canvas Files sections contain entire textbooks; auto-fetching everything would flood context. Listing first, fetching one file at a time on request, is the only safe pattern."},
		},
	}
	return toolResultJSON(ctx)
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
