// Copyright 2026 evanwboyle and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type Assignment struct {
	Description    string  `json:"description"`
	DueAt          string  `json:"due_at"`
	HtmlUrl        string  `json:"html_url"`
	Id             int     `json:"id"`
	Name           string  `json:"name"`
	PointsPossible float64 `json:"points_possible"`
}

type CanvasFile struct {
	ContentType string `json:"content-type"`
	DisplayName string `json:"display_name"`
	Filename    string `json:"filename"`
	FolderId    int    `json:"folder_id"`
	Id          int    `json:"id"`
	Size        int    `json:"size"`
	UpdatedAt   string `json:"updated_at"`
	Url         string `json:"url"`
}

type Enrollment struct {
	CourseId int             `json:"course_id"`
	Grades   json.RawMessage `json:"grades"`
	Id       int             `json:"id"`
	Type     string          `json:"type"`
}

type Page struct {
	Body      string `json:"body"`
	PageId    int    `json:"page_id"`
	Title     string `json:"title"`
	UpdatedAt string `json:"updated_at"`
	Url       string `json:"url"`
}

type Quiz struct {
	Description    string  `json:"description"`
	DueAt          string  `json:"due_at"`
	HtmlUrl        string  `json:"html_url"`
	Id             int     `json:"id"`
	PointsPossible float64 `json:"points_possible"`
	QuestionCount  int     `json:"question_count"`
	Title          string  `json:"title"`
}
